---
- name: grub2-mkconfig
  ansible.builtin.command: grub2-mkconfig -o /boot/efi/EFI/almalinux/grub.cfg
  changed_when: true

- name: augenrules
  ansible.builtin.command: augenrules --load
  changed_when: true
