---
# SRG-OS-000445-GPOS-00199 (aide)
# SRG-OS-000446-GPOS-00200
# SRG-OS-000363-GPOS-00150
- name: Initialise AIDE
  ansible.builtin.command: aide --init
  args:
    creates: /var/lib/aide/aide.db.*
  tags: aide

- name: Backup AIDE
  ansible.builtin.command: mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz
  args:
    creates: /var/lib/aide/aide.db.gz
  tags: aide

# SRG-OS-000257-GPOS-00098 (auditd)
# SRG-OS-000278-GPOS-00108 (crypto)
- name: Configure AIDE to protect the integrity of audit tools
  ansible.builtin.blockinfile:
    path: /etc/aide.conf
    block: |
      /usr/sbin/auditctl p+i+n+u+g+s+b+acl+xattrs+sha512
      /usr/sbin/auditd p+i+n+u+g+s+b+acl+xattrs+sha512
      /usr/sbin/ausearch p+i+n+u+g+s+b+acl+xattrs+sha512
      /usr/sbin/aureport p+i+n+u+g+s+b+acl+xattrs+sha512
      /usr/sbin/autrace p+i+n+u+g+s+b+acl+xattrs+sha512
      /usr/sbin/augenrules p+i+n+u+g+s+b+acl+xattrs+sha512
    backup: "{{ create_backups }}"
  tags: [aide, auditd]

- name: Replace AIDE content with content_ex
  ansible.builtin.replace:
    path: /etc/aide.conf
    regexp: '(.+) CONTENT$'
    replace: '\1 CONTENT_EX'
    backup: "{{ create_backups }}"
  tags: aide

- name: Replace AIDE /etc perms with content_ex
  ansible.builtin.replace:
    path: /etc/aide.conf
    regexp: '^/etc\s+PERMS$'
    replace: '/etc CONTENT_EX'
    backup: "{{ create_backups }}"
  tags: aide

- name: Configure AIDE cronjob
  ansible.builtin.cron:
    name: "aide"
    user: root
    special_time: daily
    cron_file: 0aide
    state: present
    job: '/usr/sbin/aide --check | /bin/mail -s "$HOSTNAME - Daily aide integrity check run" root'
  tags: [aide, cron]
