---
# SRG-OS-000023-GPOS-00006 (local banners)
# TODO: gnome banners
- name: Configure message of the day
  ansible.builtin.copy:
    content: ""
    dest: /etc/motd
    owner: root
    group: root
    mode: "0644"
  tags: banners

- name: Configure login banner
  ansible.builtin.copy:
    src: files/motd
    dest: /etc/issue
    owner: root
    group: root
    mode: "0644"
  tags: banners

# SRG-OS-000228-GPOS-00088 (remote banners)
# see also ssh.yml
- name: Configure remote banner
  ansible.builtin.copy:
    src: files/motd
    dest: /etc/issue.net
    owner: root
    group: root
    mode: "0644"
  tags: banners
