---
# SRG-OS-000033-GPOS-00014 (fips mode)
# SRG-OS-000478-GPOS-00223
# SRG-OS-000396-GPOS-00176
# SRG-OS-000125-GPOS-00065
- name: Check FIPS mode
  ansible.builtin.command: fips-mode-setup --is-enabled
  register: fips_mode
  changed_when: false
  failed_when: fips_mode.rc not in [ 0, 1, 2 ]
  tags: fips

- name: Configure FIPS mode
  ansible.builtin.command: fips-mode-setup --enable
  when: fips_mode.rc != 0
  changed_when: true
  tags: fips

# SRG-OS-000394-GPOS-00174 (crypto-policies)
# SRG-OS-000396-GPOS-00176
- name: Check crypto-policies
  ansible.builtin.command: update-crypto-policies --show
  register: crypto_policies
  changed_when: false
  tags: [fips, crypto]

- name: Configure crypto-policies
  ansible.builtin.command: update-crypto-policies --set FIPS
  when: crypto_policies.stdout != "FIPS"
  changed_when: true
  tags: [fips, crypto]

# SRG-OS-000033-GPOS-00014 (libreswan)
- name: Configure libreswan
  ansible.builtin.lineinfile:
    path: /etc/ipsec.conf
    regexp: "^include /etc/crypto-policies/back-ends/libreswan.config$"
    line: include /etc/crypto-policies/back-ends/libreswan.config
    state: present
    backup: "{{ create_backups }}"
  tags: [fips, ipsec, crypto]

# SRG-OS-000120-GPOS-00061 (krb5)
- name: Configure kerberos
  ansible.builtin.file:
    src: /usr/share/crypto-policies/FIPS/krb5.txt
    dest: /etc/crypto-policies/back-ends/krb5.config
    owner: root
    group: root
    state: link
  tags: [fips, kerberos, crypto]

# SRG-OS-000250-GPOS-00093 (openssl)
- name: Configure openssl
  ansible.builtin.lineinfile:
    path: /etc/pki/tls/openssl.cnf
    regexp: "^.include = /etc/crypto-policies/back-ends/opensslcnf.config$"
    line: .include = /etc/crypto-policies/back-ends/opensslcnf.config
    state: present
    backup: "{{ create_backups }}"
  tags: [fips, openssl, crypto]

- name: Configure TLS MinProtocol
  ansible.builtin.lineinfile:
    path: /etc/crypto-policies/back-ends/opensslcnf.config
    regexp: "^TLS.MinProtocol = TLSv1.*$"
    line: "TLS.MinProtocol = {{ tls_minprotocol }}"
    state: present
    backup: "{{ create_backups }}"
  tags: [fips, openssl, crypto]

- name: Configure TLS MaxProtocol
  ansible.builtin.lineinfile:
    path: /etc/crypto-policies/back-ends/opensslcnf.config
    regexp: "^TLS.MaxProtocol = TLSv1.*$"
    line: "TLS.MaxProtocol = {{ tls_maxprotocol }}"
    state: present
    backup: "{{ create_backups }}"
  tags: [fips, openssl, crypto]

- name: Configure DTLS MinProtocol
  ansible.builtin.lineinfile:
    path: /etc/crypto-policies/back-ends/opensslcnf.config
    regexp: "^DTLS.MinProtocol = DTLSv1.*$"
    line: "DTLS.MinProtocol = {{ dtls_minprotocol }}"
    state: present
    backup: "{{ create_backups }}"
  tags: [fips, openssl, crypto]

- name: Configure DTLS MaxProtocol
  ansible.builtin.lineinfile:
    path: /etc/crypto-policies/back-ends/opensslcnf.config
    regexp: "^DTLS.MaxProtocol = DTLSv1.*$"
    line: "DTLS.MaxProtocol = {{ dtls_maxprotocol }}"
    state: present
    backup: "{{ create_backups }}"
  tags: [fips, openssl, crypto]

# SRG-OS-000066-GPOS-00034 (pki)
- name: Configure PKI trust
  ansible.builtin.copy:
    src: files/sssd_auth_ca_db.pem
    dest: /etc/sssd/pki/sssd_auth_ca_db.pem
    owner: root
    group: root
    mode: "0644"
    checksum: 5ab60a0692ad9ca3e342e5d848736f5ee36aa195
    backup: "{{ create_backups }}"
  tags: [fips, openssl, crypto]
