---
# should run first
- name: TuxCare
  ansible.builtin.include_tasks: tuxcare.yml
  tags: always

# has to run after tuxcare
- name: Packages
  ansible.builtin.include_tasks: packages.yml
  tags: always

- name: Filesystems
  ansible.builtin.include_tasks: filesystems.yml
  tags: always

- name: Accounts
  ansible.builtin.include_tasks: accounts.yml
  tags: always

- name: Banners
  ansible.builtin.include_tasks: banners.yml
  tags: always

- name: Privileged
  ansible.builtin.include_tasks: privileged.yml
  tags: always

- name: Shells
  ansible.builtin.include_tasks: shells.yml
  tags: always

- name: SSH
  ansible.builtin.include_tasks: ssh.yml
  tags: always

- name: FIPS
  ansible.builtin.include_tasks: fips.yml
  tags: always

- name: NTP
  ansible.builtin.include_tasks: ntp.yml
  tags: always

- name: Auditd
  ansible.builtin.include_tasks: auditd.yml
  tags: always

- name: Kernel
  ansible.builtin.include_tasks: kernel.yml
  tags: always

- name: Firewall
  ansible.builtin.include_tasks: firewall.yml
  tags: always

- name: Bootloader
  ansible.builtin.include_tasks: bootloader.yml
  tags: always

- name: Permissions
  ansible.builtin.include_tasks: permissions.yml
  tags: always

- name: Miscellaneous
  ansible.builtin.include_tasks: misc.yml
  tags: always

# should run near to last
- name: AIDE
  ansible.builtin.include_tasks: aide.yml
  tags: always

# should run last
- name: Systemd
  ansible.builtin.include_tasks: systemd.yml
  tags: always
