---
# SRG-OS-000095-GPOS-00049 (port/cmdport)
# SRG-OS-000356-GPOS-00144 (sources)
# SRG-OS-000359-GPOS-00146
- name: Configure chrony.conf
  ansible.builtin.template:
    src: templates/chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: "0644"
    backup: "{{ create_backups }}"
  tags: ntp

- name: Configure chrony options
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/chronyd
    regexp: "^OPTIONS="
    line: 'OPTIONS="-F 2 -u chrony -4"'
    state: present
    backup: "{{ create_backups }}"
  tags: ntp
