---
# SRG-OS-000037-GPOS-00015 (auditd installed)
# SRG-OS-000038-GPOS-00016
# SRG-OS-000039-GPOS-00017
# SRG-OS-000040-GPOS-00018
# SRG-OS-000041-GPOS-00019
# SRG-OS-000042-GPOS-00020
# SRG-OS-000042-GPOS-00021
# SRG-OS-000051-GPOS-00024
# SRG-OS-000392-GPOS-00172
# SRG-OS-000473-GPOS-00218
# SRG-OS-000472-GPOS-00217
# SRG-OS-000474-GPOS-00219
# SRG-OS-000365-GPOS-00152
# SRG-OS-000358-GPOS-00145
# SRG-OS-000348-GPOS-00136
# SRG-OS-000349-GPOS-00137
# SRG-OS-000350-GPOS-00138
# SRG-OS-000351-GPOS-00139
# SRG-OS-000352-GPOS-00140
# SRG-OS-000353-GPOS-00141
# SRG-OS-000354-GPOS-00142
# SRG-OS-000337-GPOS-00129
# SRG-OS-000062-GPOS-00031
# SRG-OS-000054-GPOS-00025
# SRG-OS-000096-GPOS-00050 (firewalld installed)
# SRG-OS-000298-GPOS-00116
# SRG-OS-000297-GPOS-00115
# SRG-OS-000324-GPOS-00125 (sudo installed)
# SRG-OS-000342-GPOS-00133 (rsyslog installed)
# SRG-OS-000355-GPOS-00143 (chrony installed)
# SRG-OS-000359-GPOS-00146
# SRG-OS-000030-GPOS-00011 (tmux installed)
# SRG-OS-000370-GPOS-00155 (fapolicyd installed)
# SRG-OS-000375-GPOS-00160 (opensc installed)
# SRG-OS-000376-GPOS-00161 (openssl-pkcs11 installed)
# SRG-OS-000105-GPOS-00052
# SRG-OS-000378-GPOS-00163 (usbguard installed)
# SRG-OS-000394-GPOS-00174 (crypto-policies installed)
# SRG-OS-000393-GPOS-00173
# SRG-OS-000423-GPOS-00187 (openssh installed)
# SRG-OS-000424-GPOS-00188 (openssh-server installed)
# SRG-OS-000426-GPOS-00190
# SRG-OS-000445-GPOS-00199 (aide installed)
# SRG-OS-000446-GPOS-00200
# SRG-OS-000363-GPOS-00150 (s-nail installed)
# SRG-OS-000120-GPOS-00061 (rsyslog-gnutls installed)
# SRG-OS-000480-GPOS-00227 (gnutls-utils installed)
# SRG-OS-000120-GPOS-00061 (libreswan installed)
# SRG-OS-000134-GPOS-00068 (policycoreutils installed)
# SRG-OS-000479-GPOS-00224 (audispd-plugins installed)
# SRG-OS-000480-GPOS-00227 (nss-tools, rng-tools, etc. installed)
- name: Install required packages
  ansible.builtin.dnf:
    name:
      - kernel
      - openssl
      - libgcrypt
      - gnutls-utils
      - nss-tools
      - nettle
      - aide
      - audit
      - tmux
      - firewalld
      - sudo
      - chrony
      - fapolicyd
      - pcsc-lite
      - opensc
      - openssl-pkcs11
      - usbguard
      - crypto-policies
      - openssh
      - openssh-server
      - rsyslog
      - rsyslog-gnutls
      - gnutls-utils
      - libreswan
      - policycoreutils
      - s-nail
      - audispd-plugins
      - rng-tools
      - policycoreutils-python-utils
      - postfix
    state: present
  tags: dnf

# SRG-OS-000074-GPOS-00042 (ftp, vsftpd removed)
# SRG-OS-000074-GPOS-00042 (telnet removed)
# SRG-OS-000095-GPOS-00049 (telnet-server, avahi etc. removed)
# SRG-OS-000379-GPOS-00164 (autofs removed)
# SRG-OS-000114-GPOS-00059
# SRG-OS-000426-GPOS-00190 (bind removed)
- name: Remove unwanted packages
  ansible.builtin.dnf:
    name:
      - telnet
      - telnet-server
      - vsftpd
      - ftp
      - avahi
      - cups
      - sendmail
      - nfs-utils
      - ypserv
      - rsh-server
      - rsh
      - gssproxy
      - iprutils
      - tuned
      - tftp-server
      - tftp-client
      - quagga
      - xorg-x11-server-common
      - autofs
      - iwl*-firmware
      - bind
    state: absent
  tags: dnf

# SRG-OS-000480-GPOS-00227 (patches)
- name: Install patches and updates
  ansible.builtin.dnf:
    name: "*"
    state: latest
  tags: dnf

# immediately restart NetworkManager as when its
# updated it will refuse connections from nmcli
- name: Bounce NetworkManager
  ansible.builtin.systemd_service:
    name: NetworkManager.service
    state: restarted
  tags: dnf

- name: Clean up packages
  ansible.builtin.dnf:
    autoremove: true
  tags: dnf

# SRG-OS-000437-GPOS-00194 (clean requirements)
# SRG-OS-000366-GPOS-00153 (gpgcheck)
# TODO: enable repo_gpgcheck when signing server is ready
- name: Configure DNF
  ansible.builtin.copy:
    src: files/dnf.conf
    dest: /etc/dnf/dnf.conf
    mode: "0644"
    owner: root
    group: root
  tags: dnf

- name: Find repo files
  ansible.builtin.find:
    paths: /etc/yum.repos.d
    patterns: "*.repo"
  register: repofiles
  tags: dnf

- name: Configure gpgcheck
  ansible.builtin.replace:
    path: "{{ item.path }}"
    regexp: "^gpgcheck.*$"
    replace: "gpgcheck=1"
    mode: "0644"
    backup: "{{ create_backups }}"
  with_items: "{{ repofiles.files }}"
  tags: dnf

# SRG-OS-000480-GPOS-00227 (modified rpms)
# SRG-OS-000396-GPOS-00176 (modified crypto-policies)
- name: Find modified packages
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      rpm -Va --noconfig | awk '$1 ~ /..5/ && $2 != "c"'
  changed_when: false
  failed_when: false
  register: modified_rpms
  tags: dnf

- name: List modified packages
  ansible.builtin.debug:
    msg: "{{ modified_rpms.stdout_lines }}"
  when: modified_rpms.stdout_lines | length > 0
  tags: dnf

# https://almalinux.org/security/
- name: Verify the AlmaLinux GPG key
  ansible.builtin.rpm_key:
    key: https://repo.almalinux.org/almalinux/RPM-GPG-KEY-AlmaLinux-9
    state: present
    validate_certs: true
    fingerprint: BF18 AC28 7617 8908 D6E7  1267 D36C B86C B86B 3716
  tags: dnf
