---
# SRG-OS-000206-GPOS-00084 (755 or better)
- name: Configure /var/log permissions
  ansible.builtin.file:
    path: /var/log
    owner: root
    group: root
    mode: "u=rwx,g-w,o-w"
  tags: perms

# SRG-OS-000206-GPOS-00084 (640 or better)
- name: Configure /var/log/messages permissions
  ansible.builtin.file:
    path: /var/log/messages
    owner: root
    group: root
    mode: "u=rw,g-wx,o-rwx"
  tags: perms

# SRG-OS-000259-GPOS-00100 (755 or better)
- name: Configure library directories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: "u-w,g-w,o-w"
  with_items:
    - /usr/lib
    - /usr/lib64
  tags: perms

# TODO: fix perms instead of just listing (dangerous)
- name: Find commands with weak permissions
  ansible.builtin.command:
    cmd: >
      find /usr/bin /usr/sbin /usr/libexec /usr/local/bin /usr/local/sbin
      -type f \( ! -user root -o ! -group root \) -perm /022 -exec ls -l {} \;
  changed_when: false
  register: weak_commands
  tags: perms

- name: List commands with weak permissions
  ansible.builtin.debug:
    msg: "{{ weak_commands.stdout_lines | list }}"
  when: weak_commands.stdout_lines | length > 0
  tags: perms

- name: Find libraries with weak permissions
  ansible.builtin.command:
    cmd: >
      find /usr/lib /usr/lib64 -type f \( ! -user root -o ! -group root \)
      -perm /022 -exec ls -l {} \;
  changed_when: false
  register: weak_libs
  tags: perms

- name: List libraries with weak permissions
  ansible.builtin.debug:
    msg: "{{ weak_libs.stdout_lines | list }}"
  when: weak_libs.stdout_lines | length > 0
  tags: perms

# SRG-OS-000480-GPOS-00227 (cron)
- name: Configure cron directories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: "0700"
  with_items:
    - /etc/cron.d
    - /etc/cron.daily
    - /etc/cron.hourly
    - /etc/cron.weekly
    - /etc/cron.monthly
  tags: [perms, cron]

- name: Configure crontab
  ansible.builtin.file:
    path: /etc/crontab
    owner: root
    group: root
    mode: "0600"
  tags: [perms, cron]

- name: Configure passwd permissions
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - /etc/group
    - /etc/group-
    - /etc/passwd
    - /etc/passwd-
  tags: perms

- name: Configure shadow permissions
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: "0000"
  with_items:
    - /etc/shadow
    - /etc/shadow-
    - /etc/gshadow
    - /etc/gshadow-
  tags: perms

# SRG-OS-000138-GPOS-00069 (world-write)
- name: Find world-writable directories
  ansible.builtin.command: find / -type d -perm -0002 -not -perm -1000 -uid +0 -print
  register: world_writable
  changed_when: false
  tags: perms

- name: List world-writable directories not owned by root, without the sticky bit
  ansible.builtin.debug:
    msg: "{{ world_writable.stdout_lines }}"
  when: world_writable.stdout_lines | length > 0
  tags: perms

# SRG-OS-000480-GPOS-00227 (orphans)
- name: Find files with no owner or group
  ansible.builtin.command: find / \( -type f -o -type d \) \( -nouser -o -nogroup \) -print
  register: orphaned_files
  changed_when: false
  failed_when: false
  tags: perms

- name: List files with no owner or group
  ansible.builtin.debug:
    msg: "{{ orphaned_files.stdout_lines }}"
  when: orphaned_files.stdout_lines | length > 0
  tags: perms
