---
# SRG-OS-000373-GPOS-00158 (pam)
- name: Configure pam sudo
  ansible.builtin.copy:
    src: files/sudo
    dest: /etc/pam.d/sudo
    owner: root
    group: root
    mode: "0644"
  tags:
    - pam
    - privileged

# SRG-OS-000373-GPOS-00157 (restrict su)
# SRG-OS-000312-GPOS-00124
# SRG-OS-000312-GPOS-00122
# SRG-OS-000312-GPOS-00123
# SRG-OS-000373-GPOS-00158
- name: Configure pam su
  ansible.builtin.copy:
    src: files/su
    dest: /etc/pam.d/su
    owner: root
    group: root
    mode: "0644"
  tags:
    - pam
    - privileged

# SRG-OS-000373-GPOS-00156 (sudo)
- name: Configure sudo
  ansible.builtin.copy:
    src: files/sudoers
    dest: /etc/sudoers
    owner: root
    group: root
    mode: "0440"
  tags: privileged
