---
# SRG-OS-000028-GPOS-00009 (tmux login)
- name: Enable tmux for logins
  ansible.builtin.copy:
    src: files/tmux.sh
    dest: /etc/profile.d/tmux.sh
    owner: root
    group: root
    mode: "0644"
  tags: [shells, tmux]

# SRG-OS-000028-GPOS-00009 (tmux shell)
- name: Remove tmux from /etc/shells
  ansible.builtin.lineinfile:
    path: /etc/shells
    regexp: "^/.*/tmux.*$"
    state: absent
    backup: "{{ create_backups }}"
  tags: [shells, tmux]

# SRG-OS-000028-GPOS-00009 (tmux lock)
# SRG-OS-000029-GPOS-00010 (tmux timeout)
- name: Configure tmux
  ansible.builtin.template:
    src: templates/tmux.conf.j2
    dest: /etc/tmux.conf
    owner: root
    group: root
    mode: "0644"
  tags: [shells, tmux]

# SRG-OS-000029-GPOS-00010 (timeout)
# SRG-OS-000281-GPOS-0011
# SRG-OS-000163-GPOS-000721
# SRG-OS-000480-GPOS-00228 (umask)
- name: Configure bash
  ansible.builtin.template:
    src: templates/profile.sh.j2
    dest: /etc/profile.d/stig.sh
    owner: root
    group: root
    mode: "0644"
  tags: shells

- name: Configure csh
  ansible.builtin.template:
    src: templates/profile.csh.j2
    dest: /etc/profile.d/stig.csh
    owner: root
    group: root
    mode: "0644"
  tags: shells

# SRG-OS-000480-GPOS-00227 (system account shells)
- name: Find system accounts
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      awk -F: '($1!~/^(root|halt|sync|shutdown|nfsnobody)$/ && $NF !~ "nologin" && $3<1000) {print $1}' /etc/passwd
  register: system_accounts
  changed_when: false
  tags: shells

- name: Configure system account false shells
  ansible.builtin.user:
    shell: /sbin/nologin
    name: "{{ item }}"
  with_items: "{{ system_accounts.stdout_lines }}"
  when: system_accounts.stdout_lines | length > 0
  tags: shells
