---
- name: 1.1.1.1 Ensure cramfs kernel module is not available
  ansible.builtin.copy:
    src: files/modprobe/cramfs.conf
    dest: /etc/modprobe.d/cramfs.conf
    owner: root
    group: root
    mode: "644"
  tags: modprobe

- name: 1.1.1.2 Ensure freevxfs kernel module is not available
  ansible.builtin.copy:
    src: files/modprobe/freevxfs.conf
    dest: /etc/modprobe.d/freevxfs.conf
    owner: root
    group: root
    mode: "644"
  tags: modprobe

- name: 1.1.1.3 Ensure hfs kernel module is not available
  ansible.builtin.copy:
    src: files/modprobe/hfs.conf
    dest: /etc/modprobe.d/hfs.conf
    owner: root
    group: root
    mode: "644"
  tags: modprobe

- name: 1.1.1.4 Ensure hfsplus kernel module is not available
  ansible.builtin.copy:
    src: files/modprobe/hfs.conf
    dest: /etc/modprobe.d/hfs.conf
    owner: root
    group: root
    mode: "644"
  tags: modprobe

- name: 1.1.1.5 Ensure jffs2 kernel module is not available
  ansible.builtin.copy:
    src: files/modprobe/jffs2.conf
    dest: /etc/modprobe.d/jffs2.conf
    owner: root
    group: root
    mode: "644"
  tags: modprobe

- name: 1.1.1.6 Ensure overlayfs kernel module is not available
  ansible.builtin.copy:
    src: files/modprobe/overlayfs.conf
    dest: /etc/modprobe.d/overlayfs.conf
    owner: root
    group: root
    mode: "644"
  tags: modprobe

- name: 1.1.1.7 Ensure squashfs kernel module is not available
  ansible.builtin.copy:
    src: files/modprobe/squashfs.conf
    dest: /etc/modprobe.d/squashfs.conf
    owner: root
    group: root
    mode: "644"
  tags: modprobe

# udf is required by azure
- name: 1.1.1.8 Ensure udf kernel module is not available
  ansible.builtin.copy:
    src: files/modprobe/udf.conf
    dest: /etc/modprobe.d/udf.conf
    owner: root
    group: root
    mode: "644"
  tags: modprobe

- name: 1.1.1.9 Ensure usb-storage kernel module is not available
  ansible.builtin.copy:
    src: files/modprobe/usb-storage.conf
    dest: /etc/modprobe.d/usb-storage.conf
    owner: root
    group: root
    mode: "644"
  tags: modprobe

# defaults to 50% of ram
# 1.1.2.1.1 Ensure /tmp is a separate partition
# 1.1.2.1.2 Ensure nodev option set on /tmp partition
# 1.1.2.1.3 Ensure nosuid option set on /tmp partition
# 1.1.2.1.4 Ensure noexec option set on /tmp partition
- name: 1.1.2.1 Configure /tmp
  ansible.posix.mount:
    path: /tmp
    fstype: tmpfs
    src: tmpfs
    opts: defaults,noexec,nosuid,nodev
    state: present
  tags: fstab

# 1.1.2.2.1 Ensure /dev/shm is a separate partition
# 1.1.2.2.2 Ensure nodev option set on /dev/shm partition
# 1.1.2.2.3 Ensure nosuid option set on /dev/shm partition
# 1.1.2.2.4 Ensure noexec option set on /dev/shm partition
- name: 1.1.2.2 Configure /dev/shm
  ansible.posix.mount:
    path: /dev/shm
    fstype: tmpfs
    src: tmpfs
    opts: defaults,noexec,nosuid,nodev
    state: present
  tags: fstab

# 1.1.2.3.1 Ensure separate partition exists for /home
# 1.1.2.3.2 Ensure nodev option set on /home partition
# 1.1.2.3.3 Ensure nosuid option set on /home partition
- name: 1.1.2.3 Configure /home
  ansible.posix.mount:
    path: /home
    fstype: xfs
    src: /dev/mapper/rootvg-home
    opts: defaults,nodev,nosuid
    state: present
  tags: fstab

# 1.1.2.4.1 Ensure separate partition exists for /var
# 1.1.2.4.2 Ensure nodev option set on /var partition
# 1.1.2.4.3 Ensure nosuid option set on /var partition
- name: 1.1.2.4 Configure /var
  ansible.posix.mount:
    path: /var
    fstype: xfs
    src: /dev/mapper/rootvg-var
    opts: defaults,nodev,nosuid
    state: present
  tags: fstab

# 1.1.2.5.1 Ensure separate partition exists for /var/tmp
# 1.1.2.5.2 Ensure nodev option set on /var/tmp partition
# 1.1.2.5.3 Ensure nosuid option set on /var/tmp partition
# 1.1.2.5.4 Ensure noexec option set on /var/tmp partition
- name: 1.1.2.5 Configure /var/tmp
  ansible.posix.mount:
    path: /var/tmp
    fstype: xfs
    src: /dev/mapper/rootvg-vartmp
    opts: defaults,noexec,nosuid,nodev
    state: present
  tags: fstab

# 1.1.2.6.1 Ensure separate partition exists for /var/log
# 1.1.2.6.2 Ensure nodev option set on /var/log partition
# 1.1.2.6.3 Ensure nosuid option set on /var/log partition
# 1.1.2.6.4 Ensure noexec option set on /var/log partition
- name: 1.1.2.6 Configure /var/log
  ansible.posix.mount:
    path: /var/log
    fstype: xfs
    src: /dev/mapper/rootvg-log
    opts: defaults,noexec,nosuid,nodev
    state: present
  tags: fstab

# 1.1.2.7.1 Ensure separate partition exists for /var/log/audit
# 1.1.2.7.2 Ensure nodev option set on /var/log/audit partition
# 1.1.2.7.3 Ensure nosuid option set on /var/log/audit partition
# 1.1.2.7.4 Ensure noexec option set on /var/log/audit partition
- name: 1.1.2.7 Configure /var/log/audit
  ansible.posix.mount:
    path: /var/log/audit
    fstype: xfs
    src: /dev/mapper/rootvg-audit
    opts: defaults,noexec,nosuid,nodev
    state: present
  tags: fstab
