---
# 1.7.4 Ensure permissions on /etc/motd are configured
- name: 1.7.1 Ensure message of the day is configured properly
  ansible.builtin.copy:
    src: files/empty
    dest: /etc/motd
    owner: root
    group: root
    mode: "644"
  tags: banners

# 1.7.5 Ensure permissions on /etc/issue are configured
- name: 1.7.2 Ensure local login warning banner is configured properly
  ansible.builtin.copy:
    src: files/motd
    dest: /etc/issue
    owner: root
    group: root
    mode: "644"
  tags: banners

# 1.7.6 Ensure permissions on /etc/issue.net are configured
- name: 1.7.3 Ensure remote login warning banner is configured properly
  ansible.builtin.copy:
    src: files/motd
    dest: /etc/issue.net
    owner: root
    group: root
    mode: "644"
  tags: banners
