---
- name: 2.3.1 Ensure ftp client is not installed
  ansible.builtin.dnf:
    name: ftp
    state: absent
    autoremove: true
  tags:
    - clients
    - dnf

- name: 2.3.2 Ensure LDAP client is not installed
  ansible.builtin.dnf:
    name: openldap-clients
    state: absent
    autoremove: true
  tags:
    - clients
    - dnf

- name: 2.3.3 Ensure nis client is not installed
  ansible.builtin.dnf:
    name: ypbind
    state: absent
    autoremove: true
  tags:
    - clients
    - dnf

- name: 2.3.4 Ensure telnet client is not installed
  ansible.builtin.dnf:
    name: telnet
    state: absent
    autoremove: true
  tags:
    - clients
    - dnf

- name: 2.3.5 Ensure tftp client is not installed
  ansible.builtin.dnf:
    name: tftp
    state: absent
    autoremove: true
  tags:
    - clients
    - dnf
