---
- name: 5.2.1.1 Ensure audit is installed
  ansible.builtin.dnf:
    name: audit
    state: present
  tags:
    - dnf
    - auditd

# 5.2.1.3 Ensure audit_backlog_limit is sufficient
- name: 5.2.1.2 Ensure auditing for processes that start prior to auditd is enabled
  ansible.builtin.command: grubby --update-kernel=ALL --args="audit=1 audit_backlog_limit=8192"
  changed_when: false
  tags: auditd

- name: 5.2.1.4 Ensure auditd service is enabled
  ansible.builtin.systemd:
    name: auditd
    enabled: true
  tags: auditd

- name: 5.2.2.1 Ensure audit log storage size is configured
  ansible.builtin.lineinfile:
    path: /etc/audit/auditd.conf
    state: present
    regexp: '^max_log_file\s*\=\s*\d+$'
    line: "max_log_file = 8"
  tags: auditd

- name: 5.2.2.2 Ensure audit logs are not automatically deleted
  ansible.builtin.lineinfile:
    path: /etc/audit/auditd.conf
    state: present
    regexp: '^max_log_file_action\s*\=\s*.*$'
    line: "max_log_file_action = keep_logs"
  tags: auditd

- name: 5.2.2.3 Ensure system is disabled when audit logs are full
  ansible.builtin.lineinfile:
    path: /etc/audit/auditd.conf
    state: present
    regexp: '^disk_full_action\s*\=\s*.*$'
    line: "disk_full_action = single"
  tags: auditd

- name: 5.2.2.4 Ensure system warns when audit logs are low on space
  ansible.builtin.lineinfile:
    path: /etc/audit/auditd.conf
    state: present
    regexp: '^space_left_action\s*\=\s*.*$'
    line: "space_left_action = single"
  tags: auditd

# 5.2.4.5 Ensure audit configuration files are 640 or more restrictive
# 5.2.4.6 Ensure audit configuration files are owned by root
# 5.2.4.7 Ensure audit configuration files belong to group root
- name: 5.2.3.1 Ensure changes to system administration scope (sudoers) is collected
  ansible.builtin.copy:
    src: files/auditd/50-scope.rules
    dest: /etc/audit/rules.d/50-scope.rules
    mode: "644"
    owner: root
    group: root
  notify: augenrules
  tags: auditd

- name: 5.2.3.2 Ensure actions as another user are always logged
  ansible.builtin.copy:
    src: files/auditd/50-user_emulation.rules
    dest: /etc/audit/rules.d/50-user_emulation.rules
    mode: "644"
    owner: root
    group: root
  notify: augenrules
  tags: auditd

- name: 5.2.3.3 Ensure events that modify the sudo log file are collected
  ansible.builtin.copy:
    src: files/auditd/50-sudo.rules
    dest: /etc/audit/rules.d/50-sudo.rules
    mode: "644"
    owner: root
    group: root
  notify: augenrules
  tags: auditd

- name: 5.2.3.4 Ensure events that modify date and time information are collected
  ansible.builtin.copy:
    src: files/auditd/50-time-change.rules
    dest: /etc/audit/rules.d/50-time-change.rules
    mode: "644"
    owner: root
    group: root
  notify: augenrules
  tags: auditd

# added /etc/NetworkManager/ although not required (yet)
- name: 5.2.3.5 Ensure events that modify the system's network environment are collected
  ansible.builtin.copy:
    src: files/auditd/50-system_local.rules
    dest: /etc/audit/rules.d/50-system_local.rules
    mode: "644"
    owner: root
    group: root
  notify: augenrules
  tags: auditd

- name: 5.2.3.6 Ensure use of privileged commands are collected
  ansible.builtin.copy:
    src: files/auditd/50-privileged.rules
    dest: /etc/audit/rules.d/50-privileged.rules
    mode: "644"
    owner: root
    group: root
  notify: augenrules
  tags: auditd

- name: 5.2.3.7 Ensure unsuccessful file access attempts are collected
  ansible.builtin.copy:
    src: files/auditd/50-access.rules
    dest: /etc/audit/rules.d/50-access.rules
    mode: "644"
    owner: root
    group: root
  notify: augenrules
  tags: auditd

- name: 5.2.3.8 Ensure events that modify user/group information are collected
  ansible.builtin.copy:
    src: files/auditd/50-identity.rules
    dest: /etc/audit/rules.d/50-identity.rules
    mode: "644"
    owner: root
    group: root
  notify: augenrules
  tags: auditd

- name: 5.2.3.9 Ensure discretionary access control permission modification events are collected
  ansible.builtin.copy:
    src: files/auditd/50-perm_mod.rules
    dest: /etc/audit/rules.d/50-perm_mod.rules
    mode: "644"
    owner: root
    group: root
  notify: augenrules
  tags: auditd

- name: 5.2.3.10 Ensure successful file system mounts are collected
  ansible.builtin.copy:
    src: files/auditd/50-mounts.rules
    dest: /etc/audit/rules.d/50-mounts.rules
    mode: "644"
    owner: root
    group: root
  notify: augenrules
  tags: auditd

- name: 5.2.3.11 Ensure session initiation information is collected
  ansible.builtin.copy:
    src: files/auditd/50-session.rules
    dest: /etc/audit/rules.d/50-session.rules
    mode: "644"
    owner: root
    group: root
  notify: augenrules
  tags: auditd

- name: 5.2.3.12 Ensure login and logout events are collected
  ansible.builtin.copy:
    src: files/auditd/50-login.rules
    dest: /etc/audit/rules.d/50-login.rules
    mode: "644"
    owner: root
    group: root
  notify: augenrules
  tags: auditd

- name: 5.2.3.13 Ensure file deletion events by users are collected
  ansible.builtin.copy:
    src: files/auditd/50-delete.rules
    dest: /etc/audit/rules.d/50-delete.rules
    mode: "644"
    owner: root
    group: root
  notify: augenrules
  tags: auditd

- name: 5.2.3.14 Ensure events that modify the system's Mandatory Access Controls are collected
  ansible.builtin.copy:
    src: files/auditd/50-MAC-policy.rules
    dest: /etc/audit/rules.d/50-MAC-policy.rules
    mode: "644"
    owner: root
    group: root
  notify: augenrules
  tags: auditd

# 5.2.3.16 Ensure successful and unsuccessful attempts to use the setfacl command are recorded
# 5.2.3.17 Ensure successful and unsuccessful attempts to use the chacl command are recorded
- name: 5.2.3.15 Ensure successful and unsuccessful attempts to use the chcon command are recorded
  ansible.builtin.copy:
    src: files/auditd/50-perm_chng.rules
    dest: /etc/audit/rules.d/50-perm_chng.rules
    mode: "644"
    owner: root
    group: root
  notify: augenrules
  tags: auditd

- name: 5.2.3.18 Ensure successful and unsuccessful attempts to use the usermod command are recorded
  ansible.builtin.copy:
    src: files/auditd/50-usermod.rules
    dest: /etc/audit/rules.d/50-usermod.rules
    mode: "644"
    owner: root
    group: root
  notify: augenrules
  tags: auditd

- name: 5.2.3.19 Ensure kernel module loading unloading and modification is collected
  ansible.builtin.copy:
    src: files/auditd/50-kernel_modules.rules
    dest: /etc/audit/rules.d/50-kernel_modules.rules
    mode: "644"
    owner: root
    group: root
  notify: augenrules
  tags: auditd

- name: 5.2.3.20 Ensure the audit configuration is immutable
  ansible.builtin.copy:
    src: files/auditd/99-finalize.rules
    dest: /etc/audit/rules.d/99-finalize.rules
    mode: "644"
    owner: root
    group: root
  notify: augenrules
  tags: auditd

# 700 is the default
- name: 5.2.4.1 Ensure the audit log directory is 0750 or more restrictive
  ansible.builtin.file:
    path: /var/log/audit/
    owner: root
    group: root
    mode: "700"
  tags: auditd

# 600 is the default and 400 for old logs
- name: 5.2.4.2 Ensure audit log files are mode 0640 or less permissive
  ansible.builtin.command: find /var/log/audit/ -type f -exec chmod 0600 {} \;
  changed_when: false
  tags:
    - auditd
    - skip_ansible_lint

- name: 5.2.4.3 Ensure only authorized users own audit log files
  ansible.builtin.command: find /var/log/audit/ -type f -exec chown root:root {} \;
  changed_when: false
  tags:
    - auditd
    - skip_ansible_lint

- name: 5.2.4.4 Ensure only authorized groups are assigned ownership of audit log files
  ansible.builtin.lineinfile:
    path: /etc/audit/auditd.conf
    state: present
    regexp: '^log_group\s*\=\s*\d+$'
    line: "log_group = root"
  tags: auditd

- name: 5.2.4.8 Ensure audit tools are 755 or more restrictive
  ansible.builtin.command: chmod go-w /sbin/auditctl /sbin/aureport /sbin/ausearch /sbin/autrace /sbin/auditd /sbin/augenrules
  changed_when: false
  tags:
    - auditd
    - skip_ansible_lint

# 5.2.4.10 Ensure audit tools belong to group root
- name: 5.2.4.9 Ensure audit tools are owned by root
  ansible.builtin.command: chown root:root /sbin/auditctl /sbin/aureport /sbin/ausearch /sbin/autrace /sbin/auditd /sbin/augenrules
  changed_when: false
  tags:
    - auditd
    - skip_ansible_lint
