---
- name: 6.1.1 Ensure permissions on /etc/passwd are configured
  ansible.builtin.file:
    path: /etc/passwd
    owner: root
    group: root
    mode: "644"
  tags: perms

- name: 6.1.2 Ensure permissions on /etc/passwd- are configured
  ansible.builtin.file:
    path: /etc/passwd-
    owner: root
    group: root
    mode: "644"
  tags: perms

- name: 6.1.3 Ensure permissions on /etc/opasswd are configured
  ansible.builtin.file:
    path: /etc/opasswd
    owner: root
    group: root
    mode: "600"
    state: touch
    modification_time: preserve
    access_time: preserve
  tags: perms

- name: 6.1.4 Ensure permissions on /etc/group are configured
  ansible.builtin.file:
    path: /etc/group
    owner: root
    group: root
    mode: "644"
  tags: perms

- name: 6.1.5 Ensure permissions on /etc/group- are configured
  ansible.builtin.file:
    path: /etc/group-
    owner: root
    group: root
    mode: "644"
  tags: perms

- name: 6.1.6 Ensure permissions on /etc/shadow are configured
  ansible.builtin.file:
    path: /etc/shadow
    owner: root
    group: root
    mode: "000"
  tags: perms

- name: 6.1.7 Ensure permissions on /etc/shadow- are configured
  ansible.builtin.file:
    path: /etc/shadow-
    owner: root
    group: root
    mode: "000"
  tags: perms

- name: 6.1.8 Ensure permissions on /etc/gshadow are configured
  ansible.builtin.file:
    path: /etc/gshadow
    owner: root
    group: root
    mode: "000"
  tags: perms

- name: 6.1.9 Ensure permissions on /etc/gshadow- are configured
  ansible.builtin.file:
    path: /etc/gshadow-
    owner: root
    group: root
    mode: "000"
  tags: perms

- name: 6.1.10 Ensure permissions on /etc/shells are configured
  ansible.builtin.file:
    path: /etc/shells
    owner: root
    group: root
    mode: "644"
  tags: perms
