---
- name: 1.4.1 Ensure bootloader password is set
  ansible.builtin.expect:
    command: grub2-setpassword
    responses:
      Enter password: "{{ grub_password }}"
      Confirm password: "{{ grub_password }}"
    creates: /boot/grub2/user.cfg
  notify: grub2-mkconfig
  no_log: true
  tags: grub

- name: 1.4.2 Ensure access to bootloader config is configured
  ansible.builtin.file:
    path: /boot/grub2/grub.cfg
    owner: root
    group: root
    mode: "0700"
  tags: grub

- name: Set grubenv permissions
  ansible.builtin.file:
    path: /boot/grub2/grubenv
    owner: root
    group: root
    mode: "0600"
  tags: grub

- name: Set user.cfg permissions
  ansible.builtin.file:
    path: /boot/grub2/user.cfg
    owner: root
    group: root
    mode: "0600"
  tags: grub

# extra
- name: Set grub timeout
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: "^GRUB_TIMEOUT="
    line: "GRUB_TIMEOUT=1"
    state: present
    backup: "{{ create_backups }}"
  notify: grub2-mkconfig
  tags: grub
