---
- name: 1.5.1 Ensure address space layout randomization is enabled
  ansible.builtin.copy:
    src: files/sysctl/60-aslr.conf
    dest: /etc/sysctl.d/60-aslr.conf
    mode: "0644"
    owner: root
    group: root
  tags:
    - hardening
    - sysctl

# may soon update to 2
- name: 1.5.2 Ensure ptrace_scope is restricted
  ansible.builtin.copy:
    src: files/sysctl/60-ptrace_scope.conf
    dest: /etc/sysctl.d/60-ptrace_scope.conf
    mode: "0644"
    owner: root
    group: root
  tags:
    - hardening
    - sysctl

- name: 1.5.3 Ensure core dump backtraces are disabled
  community.general.ini_file:
    path: /etc/systemd/coredump.conf
    section: Coredump
    option: ProcessSizeMax
    value: 0
    state: present
    no_extra_spaces: true
    mode: "0644"
    backup: "{{ create_backups }}"
  tags:
    - hardening
    - systemd

- name: 1.5.4 Ensure core dump storage is disabled
  community.general.ini_file:
    path: /etc/systemd/coredump.conf
    section: Coredump
    option: Storage
    value: none
    state: present
    no_extra_spaces: true
    mode: "0644"
    backup: "{{ create_backups }}"
  tags:
    - hardening
    - systemd
