---
- name: 1.6.2 Ensure system wide crypto policy is not set in sshd configuration
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/sshd
    regexp: "^CRYPTO_POLICY.*$"
    state: absent
    backup: "{{ create_backups }}"
  tags:
    - ssh
    - crypto

# 5.1.5 Ensure sshd KexAlgorithms is configured
- name: 1.6.3 Ensure system wide crypto policy disables sha1 hash and signature support
  ansible.builtin.copy:
    src: files/crypto/NO-SHA1.pmod
    dest: /etc/crypto-policies/policies/modules/NO-SHA1.pmod
    mode: "0644"
    owner: root
    group: root
  tags:
    - ssh
    - crypto

# 5.1.6 Ensure sshd MACs are configured
- name: 1.6.4 Ensure system wide crypto policy disables macs less than 128 bits
  ansible.builtin.copy:
    src: files/crypto/NO-WEAKMAC.pmod
    dest: /etc/crypto-policies/policies/modules/NO-WEAKMAC.pmod
    mode: "0644"
    owner: root
    group: root
  tags:
    - ssh
    - crypto

- name: 1.6.5 Ensure system wide crypto policy disables cbc for ssh
  ansible.builtin.copy:
    src: files/crypto/NO-SSHCBC.pmod
    dest: /etc/crypto-policies/policies/modules/NO-SSHCBC.pmod
    mode: "0644"
    owner: root
    group: root
  tags:
    - ssh
    - crypto

# CVE-2023-48795
- name: 1.6.6 Ensure system wide crypto policy disables chacha20-poly1305 for ssh
  ansible.builtin.copy:
    src: files/crypto/NO-SSHCHACHA20.pmod
    dest: /etc/crypto-policies/policies/modules/NO-SSHCHACHA20.pmod
    mode: "0644"
    owner: root
    group: root
  tags:
    - ssh
    - crypto

# CVE-2023-48795
- name: 1.6.7 Ensure system wide crypto policy disables EtM for ssh
  ansible.builtin.copy:
    src: files/crypto/NO-SSHETM.pmod
    dest: /etc/crypto-policies/policies/modules/NO-SSHETM.pmod
    mode: "0644"
    owner: root
    group: root
  tags:
    - ssh
    - crypto

- name: 5.1.4 Ensure sshd Ciphers are configured
  ansible.builtin.copy:
    src: files/crypto/NO-SSHWEAKCIPHERS.pmod
    dest: /etc/crypto-policies/policies/modules/NO-SSHWEAKCIPHERS.pmod
    mode: "0644"
    owner: root
    group: root
  tags:
    - ssh
    - crypto

- name: 1.6.1 Ensure system wide crypto policy is not set to legacy (<9.3)
  ansible.builtin.command: update-crypto-policies --set {{ systemwide_crypto }}:NO-SSHWEAKCIPHERS:NO-SHA1:NO-WEAKMAC:NO-SSHCHACHA20:NO-SSHCBC
  changed_when: false
  when: ansible_distribution_version < '9.3'
  tags:
    - ssh
    - crypto

# only 9.3+ can disable etm
- name: 1.6.1 Ensure system wide crypto policy is not set to legacy (>=9.3)
  ansible.builtin.command: update-crypto-policies --set {{ systemwide_crypto }}:NO-SSHWEAKCIPHERS:NO-SHA1:NO-WEAKMAC:NO-SSHCHACHA20:NO-SSHCBC:NO-SSHETM
  changed_when: false
  when: ansible_distribution_version >= '9.3'
  tags:
    - ssh
    - crypto
