---
# 1.7.4 Ensure access to /etc/motd is configured
- name: 1.7.1 Ensure message of the day is configured properly
  ansible.builtin.copy:
    content: ""
    dest: /etc/motd
    owner: root
    group: root
    mode: "0644"
  tags: banners

# 1.7.5 Ensure access to /etc/issue is configured
- name: 1.7.2 Ensure local login warning banner is configured properly
  ansible.builtin.copy:
    src: files/motd
    dest: /etc/issue
    owner: root
    group: root
    mode: "0644"
  tags: banners

# 1.7.6 Ensure access to /etc/issue.net is configured
- name: 1.7.3 Ensure remote login warning banner is configured properly
  ansible.builtin.copy:
    src: files/motd
    dest: /etc/issue.net
    owner: root
    group: root
    mode: "0644"
  tags: banners
