---
- name: 2.3.1 Ensure time synchronization is in use
  ansible.builtin.dnf:
    name: chrony
    state: present
  tags:
    - dnf
    - ntp

- name: 2.3.2 Ensure chrony is configured
  ansible.builtin.blockinfile:
    path: /etc/chrony.conf
    block: |
      server {{ ntp_server }}
      bindaddress 127.0.0.1
      port 0
      cmdport 0
    backup: "{{ create_backups }}"
  tags: ntp

- name: 2.3.3 Ensure chrony is not run as the root user
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/chronyd
    regexp: "^OPTIONS="
    line: 'OPTIONS="-F 2 -u chrony -4"'
    state: present
    backup: "{{ create_backups }}"
  tags: ntp
