---
- name: 4.1 Configure a firewall utility
  ansible.builtin.systemd:
    name: nftables
    enabled: true
  tags: firewall

# 4.1.1.1 Ensure nftables base chains exist
# 4.1.1.2 Ensure host based firewall loopback traffic is configured
# 4.1.1.4 Ensure nftables established connections are configured
# 4.1.1.5 Ensure nftables default deny firewall policy
- name: 4.1.1 Configure firewall rules
  ansible.builtin.copy:
    src: files/nftables/cis.nft
    dest: /etc/nftables/cis.nft
    owner: root
    group: root
    mode: "0600"
  tags: firewall

- name: Configure nftables
  ansible.builtin.copy:
    src: files/nftables/nftables.conf
    dest: /etc/sysconfig/nftables.conf
    mode: "0600"
    owner: root
    group: root
    backup: "{{ create_backups }}"
  tags: firewall

- name: 4.1.2 Ensure nftables is installed
  ansible.builtin.dnf:
    name: nftables
    state: present
  tags: firewall

# 4.1.1.3 Ensure firewalld drops unnecessary services and ports
- name: 4.1.3 Ensure a single firewall configuration utility is in use
  ansible.builtin.dnf:
    name: firewalld
    state: absent
  tags:
    - firewall
    - dnf
