---
- name: 4.1 Configure a firewall utility
  ansible.builtin.systemd:
    name: nftables
    enabled: true
  tags: firewall

- name: 4.1.1 Ensure nftables is installed
  ansible.builtin.dnf:
    name: nftables
    state: present
  tags: firewall

- name: 4.1.2 Ensure a single firewall configuration utility is in use
  ansible.builtin.dnf:
    name: firewalld
    state: absent
  tags:
    - firewall
    - dnf

# 4.2.1 Ensure firewalld drops unnecessary services and ports
# 4.2.2 Ensure host based firewall loopback traffic is configured
# 4.3.2 Ensure nftables established connections are configured
# 4.3.3 Ensure nftables default deny firewall policy
- name: 4.3 Configure NFTables
  ansible.builtin.copy:
    src: files/nftables/cis.nft
    dest: /etc/nftables/cis.nft
    owner: root
    group: root
    mode: "0600"
  tags: firewall

- name: 4.3.1 Ensure nftables base chains exist
  ansible.builtin.copy:
    src: files/nftables/nftables.conf
    dest: /etc/sysconfig/nftables.conf
    mode: "0600"
    owner: root
    group: root
    backup: "{{ create_backups }}"
  tags: firewall
