---
# 5.1.4 Ensure SSH access is limited
# 5.1.5 Ensure sshd Banner is configured
# 5.1.6 Ensure sshd Ciphers are configured
# 5.1.7 Ensure sshd ClientAliveInterval and ClientAliveCountMax are configured
# 5.1.8 Ensure sshd DisableForwarding is enabled
# 5.1.9 Ensure sshd GSSAPIAuthentication is disabled
# 5.1.10 Ensure sshd HostbasedAuthentication is disabled
# 5.1.11 Ensure sshd IgnoreRhosts is enabled
# 5.1.12 Ensure sshd KexAlgorithms is configured
# 5.1.13 Ensure sshd LoginGraceTime is configured
# 5.1.14 Ensure sshd LogLevel is configured
# 5.1.15 Ensure sshd MACs are configured
# 5.1.16 Ensure sshd MaxAuthTries is configured
# 5.1.17 Ensure sshd MaxSessions is configured
# 5.1.18 Ensure sshd MaxStartups is configured
# 5.1.19 Ensure sshd PermitEmptyPasswords is disabled
# 5.1.20 Ensure sshd PermitRootLogin is disabled
# 5.1.21 Ensure sshd PermitUserEnvironment is disabled
# 5.1.22 Ensure sshd UsePAM is enabled
# 5.1.23 Ensure sshd crypto_policy is not set
- name: 5.1.1 Ensure permissions on /etc/ssh/sshd_config are configured
  ansible.builtin.template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0600"
    backup: "{{ create_backups }}"
  tags: ssh

- name: Find ssh private host keys
  ansible.builtin.find:
    paths: /etc/ssh
    patterns: "ssh_host_*_key"
  register: hostkeys_priv
  changed_when: false
  tags: ssh

- name: 5.1.2 Ensure permissions on SSH private host key files are configured
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: root
    group: ssh_keys
    mode: "0640"
  with_items: "{{ hostkeys_priv.files }}"
  tags: ssh

- name: Find ssh public host keys
  ansible.builtin.find:
    paths: /etc/ssh
    patterns: "ssh_host_*_key.pub"
  register: hostkeys_pub
  changed_when: false
  tags: ssh

- name: 5.1.3 Ensure permissions on SSH public host key files are configured
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: "0644"
  with_items: "{{ hostkeys_pub.files }}"
  tags: ssh
