---
- name: 5.2.1 Ensure sudo is installed
  ansible.builtin.dnf:
    name: sudo
    state: present
  tags:
    - sudo
    - dnf

- name: Configure sudoers
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^#includedir /etc/sudoers.d$"
    line: "#includedir /etc/sudoers.d"
    backup: "{{ create_backups }}"
  tags: sudo

# 5.2.6 Ensure sudo authentication timeout is configured correctly
- name: 5.2.2 Ensure sudo commands use pty
  ansible.builtin.copy:
    src: files/sudoers
    dest: /etc/sudoers.d/01_cis
    owner: root
    group: root
    mode: "0440"
  tags: sudo

- name: 5.2.3 Ensure sudo log file exists
  ansible.builtin.file:
    path: /var/log/sudo.log
    owner: root
    group: root
    mode: "0600"
    state: touch
    modification_time: preserve
    access_time: preserve
  tags: sudo

- name: Find sudo configs
  ansible.builtin.find:
    paths: /etc/sudoers.d
  register: sudoers
  tags: sudo

- name: 5.2.4 Ensure users must provide password for escalation
  ansible.builtin.lineinfile:
    path: "{{ item.path }}"
    regexp: "^.*NOPASSWD.*$"
    state: absent
  with_items: "{{ sudoers.files }}"
  tags: sudo

- name: Remove NOPASSWD from sudoers
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: "^.*NOPASSWD.*$"
    state: absent
    backup: "{{ create_backups }}"
  tags: sudo

- name: 5.2.5 Ensure re-authentication for privilege escalation is not disabled globally
  ansible.builtin.lineinfile:
    path: "{{ item.path }}"
    regexp: "^.*!authenticate.*$"
    state: absent
  with_items: "{{ sudoers.files }}"
  tags: sudo

- name: Remove !authenticate from sudoers
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: "^.*!authenticate.*$"
    state: absent
    backup: "{{ create_backups }}"
  tags: sudo

- name: Create empty sugroup
  ansible.builtin.group:
    name: "{{ su_group }}"
    state: present
  tags: sudo2

- name: 5.2.7 Ensure access to the su command is restricted
  ansible.builtin.replace:
    path: /etc/pam.d/su
    regexp: 'auth\s+required\s+pam_wheel.so.*'
    replace: "auth required pam_wheel.so use_uid group={{ su_group }}"
    backup: "{{ create_backups }}"
  tags:
    - pam
    - sudo2
