---
# 5.3.3.2.2 Ensure password length is configured
# 5.3.3.2.3 Ensure password complexity is configured
# 5.3.3.2.4 Ensure password same consecutive characters is configured
# 5.3.3.2.5 Ensure password maximum sequential characters is configured
# 5.3.3.2.6 Ensure password dictionary check is enabled
# 5.3.3.2.7 Ensure password quality is enforced for the root user
- name: 5.3.3.2.1 Ensure password number of changed characters is configured
  ansible.builtin.template:
    src: templates/pwquality.conf.j2
    dest: /etc/security/pwquality.conf
    owner: root
    group: root
    mode: "0644"
  tags: pam

# 5.3.3.1.3 Ensure password failed attempts lockout includes root account
# 5.3.3.1.2 Ensure password unlock time is configured
- name: 5.3.3.1.1 Ensure password failed attempts lockout is configured
  ansible.builtin.template:
    src: templates/faillock.conf.j2
    dest: /etc/security/faillock.conf
    owner: root
    group: root
    mode: "0644"
  tags: pam

# 5.3.3.3.2 Ensure password history is enforced for the root user
- name: 5.3.3.3.1 Ensure password history remember is configured
  ansible.builtin.template:
    src: templates/pwhistory.conf.j2
    dest: /etc/security/pwhistory.conf
    owner: root
    group: root
    mode: "0644"
  tags: pam

- name: Check for use_authtok (pam_pwhistory)
  ansible.builtin.lineinfile:
    path: /etc/pam.d/password-auth
    regexp: "^.*pam_pwhistory.so.*use_authtok.*"
    state: absent
  check_mode: true
  changed_when: false
  register: history_authtok
  tags: pam

- name: 5.3.3.3.3 Ensure pam_pwhistory includes use_authtok
  ansible.builtin.debug:
    msg: "The pam_pwhistory module is not configured with 'use_authtok'. Update the authselect password-auth file to include it."
  when: not history_authtok.found
  tags: pam

- name: Check for nullok
  ansible.builtin.lineinfile:
    path: /etc/pam.d/password-auth
    regexp: "^.*nullok.*"
    state: absent
  check_mode: true
  changed_when: false
  register: nullok
  tags: pam

- name: 5.3.3.4.1 Ensure pam_unix does not include nullok
  ansible.builtin.debug:
    msg: "The pam_unix module is configured with 'nullok'. Update the authselect password-auth file to remove it."
  when: nullok.found
  tags: pam

- name: Check for remember
  ansible.builtin.lineinfile:
    path: /etc/pam.d/password-auth
    regexp: "^.*remember.*"
    state: absent
  check_mode: true
  changed_when: false
  register: remember
  tags: pam

- name: 5.3.3.4.2 Ensure pam_unix does not include remember
  ansible.builtin.debug:
    msg: "The pam_unix module is configured with 'remember'. Update the authselect password-auth file to remove it."
  when: remember.found
  tags: pam

# using sha512 for now - already set in password-auth and login.defs
- name: 5.3.3.4.3 Ensure pam_unix includes a strong password hashing algorithm
  community.general.ini_file:
    path: /etc/libuser.conf
    section: defaults
    option: crypt_style
    value: sha512
    state: present
    mode: "0644"
    backup: "{{ create_backups }}"
  tags: pam

- name: Check for use_authtok (pam_unix)
  ansible.builtin.lineinfile:
    path: /etc/pam.d/password-auth
    regexp: "^.*pam_unix.so.*use_authtok.*"
    state: absent
  check_mode: true
  changed_when: false
  register: unix_authtok
  tags: pam

- name: 5.3.3.4.4 Ensure pam_unix includes use_authtok
  ansible.builtin.debug:
    msg: "The pam_unix module is not configured with 'use_authtok'. Update the authselect password-auth file to include it."
  when: not unix_authtok.found
  tags: pam

# run this even in check mode to register the variable
- name: Run authselect list check
  ansible.builtin.command: authselect list
  register: authselect_list
  changed_when: false
  check_mode: false
  tags: pam

# skip if already created as will error otherwise
- name: Create custom authselect profile
  ansible.builtin.command: authselect create-profile cis -b sssd
  when: '"custom/cis" not in authselect_list.stdout'
  register: authselect_create
  changed_when: authselect_create.rc == 0
  tags: pam

# run this even in check mode to register the variable
- name: Run authselect current check
  ansible.builtin.command: authselect current
  register: authselect_current
  changed_when: false
  check_mode: false
  ignore_errors: true
  tags: pam

# skip if already selected as will change otherwise and we don't want to hide that
- name: 5.3.2.1 Ensure active authselect profile includes pam modules
  ansible.builtin.command: authselect select custom/cis without-nullok with-faillock with-pwhistory --force
  when: '"custom/cis" not in authselect_current.stdout'
  register: authselect_select
  changed_when: authselect_select.rc == 0
  tags: pam

- name: Check for pam_faillock.so
  ansible.builtin.lineinfile:
    path: /etc/pam.d/password-auth
    regexp: "^.*pam_faillock.so.*"
    state: absent
  check_mode: true
  changed_when: false
  register: faillock
  tags: pam

- name: 5.3.2.2 Ensure pam_faillock module is enabled
  ansible.builtin.debug:
    msg: "The pam_faillock module is not enabled. Update the authselect password-auth file to include it."
  when: not faillock.found
  tags: pam

- name: Check for pam_pwquality.so
  ansible.builtin.lineinfile:
    path: /etc/pam.d/password-auth
    regexp: "^.*pam_pwquality.so.*"
    state: absent
  check_mode: true
  changed_when: false
  register: pwquality
  tags: pam

- name: 5.3.2.3 Ensure pam_pwquality module is enabled
  ansible.builtin.debug:
    msg: "The pam_pwquality module is not enabled. Update the authselect password-auth file to include it."
  when: not pwquality.found
  tags: pam

- name: Check for pam_pwhistory.so
  ansible.builtin.lineinfile:
    path: /etc/pam.d/password-auth
    regexp: "^.*pam_pwhistory.so.*"
    state: absent
  check_mode: true
  changed_when: false
  register: pwhistory
  tags: pam

- name: 5.3.2.4 Ensure pam_pwhistory module is enabled
  ansible.builtin.debug:
    msg: "The pam_pwhistory module is not enabled. Update the authselect password-auth file to include it."
  when: not pwhistory.found
  tags: pam

- name: Check for pam_unix.so
  ansible.builtin.lineinfile:
    path: /etc/pam.d/password-auth
    regexp: "^.*pam_unix.so.*"
    state: absent
  check_mode: true
  changed_when: false
  register: pam_unix
  tags: pam

- name: 5.3.2.5 Ensure pam_unix module is enabled
  ansible.builtin.debug:
    msg: "The pam_unix module is not enabled. Update the authselect password-auth file to include it."
  when: not pam_unix.found
  tags: pam
