---
- name: 6.2.3.1 Ensure rsyslog is installed
  ansible.builtin.dnf:
    name: rsyslog
    state: present
  tags:
    - logging
    - dnf

- name: 6.2.3.2 Ensure rsyslog service is enabled and active
  ansible.builtin.systemd:
    name: rsyslog
    enabled: true
  tags: logging

- name: 6.2.3.3 Ensure journald is configured to send logs to rsyslog
  community.general.ini_file:
    path: /etc/systemd/journald.conf
    section: Journal
    option: ForwardToSyslog
    value: "yes"
    state: present
    exclusive: true
    no_extra_spaces: true
    mode: "0644"
    backup: "{{ create_backups }}"
  tags:
    - logging
    - systemd

# 6.2.3.4 Ensure rsyslog log file creation mode is configured
# 6.2.3.6 Ensure rsyslog is configured to send logs to a remote log host
# 6.2.4.1 Ensure access to all logfiles has been configured
- name: 6.2.3.5 Ensure logging is configured
  ansible.builtin.template:
    src: templates/rsyslog.j2
    dest: /etc/rsyslog.d/cis.conf
    mode: "0600"
    owner: root
    group: root
  tags: logging

- name: 6.2.3.7 Ensure rsyslog is not configured to receive logs from a remote client
  ansible.builtin.lineinfile:
    path: /etc/rsyslog.conf
    regexp: "^.*(InputTCPServerRun|imtcp).*$"
    state: absent
    backup: "{{ create_backups }}"
  tags: logging

# 6.2.2.1.1 Ensure systemd-journal-remote is installed
# 6.2.2.1.2 Ensure systemd-journal-remote is configured
# 6.2.2.1.3 Ensure systemd-journal-remote is enabled and active
- name: 6.2.2.1.4 Ensure systemd-journal-remote service is not in use
  ansible.builtin.dnf:
    name: systemd-journal-remote
    state: absent
  tags:
    - logging
    - dnf
    - systemd

- name: 6.2.1.1 Ensure journald service is enabled and active
  ansible.builtin.systemd:
    name: systemd-journald
    enabled: true
  tags: logging

- name: 6.2.2.3 Ensure journald Compress is configured
  community.general.ini_file:
    path: /etc/systemd/journald.conf
    section: Journal
    option: Compress
    value: "yes"
    state: present
    no_extra_spaces: true
    mode: "0644"
    backup: "{{ create_backups }}"
  tags:
    - logging
    - systemd

- name: 6.2.2.4 Ensure journald Storage is configured
  community.general.ini_file:
    path: /etc/systemd/journald.conf
    section: Journal
    option: Storage
    value: persistent
    state: present
    no_extra_spaces: true
    mode: "0644"
    backup: "{{ create_backups }}"
  tags:
    - logging
    - systemd

- name: 6.2.3.8 Ensure rsyslog logrotate is configured
  ansible.builtin.copy:
    src: files/logrotate
    dest: /etc/logrotate.d/cis
    mode: "0644"
    owner: root
    group: root
  tags: logging
