---
- name: 6.3.1.1 Ensure auditd packages are installed
  ansible.builtin.dnf:
    name:
      - audit
      - audit-libs
    state: present
  tags:
    - dnf
    - auditd

# 6.3.1.3 Ensure audit_backlog_limit is sufficient
- name: 6.3.1.2 Ensure auditing for processes that start prior to auditd is enabled
  ansible.builtin.command: grubby --update-kernel=ALL --args="audit=1 audit_backlog_limit={{ auditd_audit_backlog_limit }}"
  changed_when: false
  tags: auditd

- name: 6.3.1.4 Ensure auditd service is enabled and active
  ansible.builtin.systemd:
    name: auditd
    enabled: true
  tags: auditd

- name: 6.3.2.1 Ensure audit log storage size is configured
  ansible.builtin.lineinfile:
    path: /etc/audit/auditd.conf
    state: present
    regexp: '^max_log_file\s*\=\s*\d+$'
    line: "max_log_file = {{ auditd_max_log_file_size }}"
    backup: "{{ create_backups }}"
  tags: auditd

- name: 6.3.2.2 Ensure audit logs are not automatically deleted
  ansible.builtin.lineinfile:
    path: /etc/audit/auditd.conf
    state: present
    regexp: '^max_log_file_action\s*\=\s*.*$'
    line: "max_log_file_action = {{ auditd_max_log_file_action }}"
    backup: "{{ create_backups }}"
  tags: auditd

- name: 6.3.2.4 Ensure system warns when audit logs are low on space
  ansible.builtin.lineinfile:
    path: /etc/audit/auditd.conf
    state: present
    regexp: '^space_left_action\s*\=\s*.*$'
    line: "space_left_action = {{ auditd_space_left_action }}"
    backup: "{{ create_backups }}"
  tags: auditd

- name: 6.3.2.4 Ensure system warns when audit logs are low on space (admin)
  ansible.builtin.lineinfile:
    path: /etc/audit/auditd.conf
    state: present
    regexp: '^admin_space_left_action\s*\=\s*.*$'
    line: "admin_space_left_action = {{ auditd_admin_space_left_action }}"
    backup: "{{ create_backups }}"
  tags: auditd

- name: 6.3.2.4 Ensure system warns when audit logs are low on space (email)
  ansible.builtin.lineinfile:
    path: /etc/audit/auditd.conf
    state: present
    regexp: '^action_mail_acct\s*\=\s*.*$'
    line: "action_mail_acct = root"
    backup: "{{ create_backups }}"
  tags: auditd

# 6.3.4.5 Ensure audit configuration files mode is configured
# 6.3.4.6 Ensure audit configuration files owner is configured
# 6.3.4.7 Ensure audit configuration files group owner is configured
# 6.3.3.21 Ensure the running and on disk configuration is the same
- name: 6.3.3.1 Ensure changes to system administration scope (sudoers) is collected
  ansible.builtin.copy:
    src: files/auditd/50-scope.rules
    dest: /etc/audit/rules.d/50-scope.rules
    mode: "0644"
    owner: root
    group: root
  notify: augenrules
  tags: auditd

- name: 6.3.3.2 Ensure actions as another user are always logged
  ansible.builtin.copy:
    src: files/auditd/50-user_emulation.rules
    dest: /etc/audit/rules.d/50-user_emulation.rules
    mode: "0644"
    owner: root
    group: root
  notify: augenrules
  tags: auditd

- name: 6.3.3.3 Ensure events that modify the sudo log file are collected
  ansible.builtin.copy:
    src: files/auditd/50-sudo.rules
    dest: /etc/audit/rules.d/50-sudo.rules
    mode: "0644"
    owner: root
    group: root
  notify: augenrules
  tags: auditd

- name: 6.3.3.4 Ensure events that modify date and time information are collected
  ansible.builtin.copy:
    src: files/auditd/50-time-change.rules
    dest: /etc/audit/rules.d/50-time-change.rules
    mode: "0644"
    owner: root
    group: root
  notify: augenrules
  tags: auditd

- name: 6.3.3.5 Ensure events that modify the system's network environment are collected
  ansible.builtin.copy:
    src: files/auditd/50-system_local.rules
    dest: /etc/audit/rules.d/50-system_local.rules
    mode: "0644"
    owner: root
    group: root
  notify: augenrules
  tags: auditd

- name: 6.3.3.6 Ensure use of privileged commands are collected
  ansible.builtin.copy:
    src: files/auditd/50-privileged.rules
    dest: /etc/audit/rules.d/50-privileged.rules
    mode: "0644"
    owner: root
    group: root
  notify: augenrules
  tags: auditd

- name: 6.3.3.7 Ensure unsuccessful file access attempts are collected
  ansible.builtin.copy:
    src: files/auditd/50-access.rules
    dest: /etc/audit/rules.d/50-access.rules
    mode: "0644"
    owner: root
    group: root
  notify: augenrules
  tags: auditd

- name: 6.3.3.8 Ensure events that modify user/group information are collected
  ansible.builtin.copy:
    src: files/auditd/50-identity.rules
    dest: /etc/audit/rules.d/50-identity.rules
    mode: "0644"
    owner: root
    group: root
  notify: augenrules
  tags: auditd

- name: 6.3.3.9 Ensure discretionary access control permission modification events are collected
  ansible.builtin.copy:
    src: files/auditd/50-perm_mod.rules
    dest: /etc/audit/rules.d/50-perm_mod.rules
    mode: "0644"
    owner: root
    group: root
  notify: augenrules
  tags: auditd

- name: 6.3.3.10 Ensure successful file system mounts are collected
  ansible.builtin.copy:
    src: files/auditd/50-mounts.rules
    dest: /etc/audit/rules.d/50-mounts.rules
    mode: "0644"
    owner: root
    group: root
  notify: augenrules
  tags: auditd

- name: 6.3.3.11 Ensure session initiation information is collected
  ansible.builtin.copy:
    src: files/auditd/50-session.rules
    dest: /etc/audit/rules.d/50-session.rules
    mode: "0644"
    owner: root
    group: root
  notify: augenrules
  tags: auditd

- name: 6.3.3.12 Ensure login and logout events are collected
  ansible.builtin.copy:
    src: files/auditd/50-login.rules
    dest: /etc/audit/rules.d/50-login.rules
    mode: "0644"
    owner: root
    group: root
  notify: augenrules
  tags: auditd

- name: 6.3.3.13 Ensure file deletion events by users are collected
  ansible.builtin.copy:
    src: files/auditd/50-delete.rules
    dest: /etc/audit/rules.d/50-delete.rules
    mode: "0644"
    owner: root
    group: root
  notify: augenrules
  tags: auditd

- name: 6.3.3.14 Ensure events that modify the system's Mandatory Access Controls are collected
  ansible.builtin.copy:
    src: files/auditd/50-MAC-policy.rules
    dest: /etc/audit/rules.d/50-MAC-policy.rules
    mode: "0644"
    owner: root
    group: root
  notify: augenrules
  tags: auditd

# 6.3.3.16 Ensure successful and unsuccessful attempts to use the setfacl command are collected
# 6.3.3.17 Ensure successful and unsuccessful attempts to use the chacl command are collected
- name: 6.3.3.15 Ensure successful and unsuccessful attempts to use the chcon command are collected
  ansible.builtin.copy:
    src: files/auditd/50-perm_chng.rules
    dest: /etc/audit/rules.d/50-perm_chng.rules
    mode: "0644"
    owner: root
    group: root
  notify: augenrules
  tags: auditd

- name: 6.3.3.18 Ensure successful and unsuccessful attempts to use the usermod command are collected
  ansible.builtin.copy:
    src: files/auditd/50-usermod.rules
    dest: /etc/audit/rules.d/50-usermod.rules
    mode: "0644"
    owner: root
    group: root
  notify: augenrules
  tags: auditd

- name: 6.3.3.19 Ensure kernel module loading unloading and modification is collected
  ansible.builtin.copy:
    src: files/auditd/50-kernel_modules.rules
    dest: /etc/audit/rules.d/50-kernel_modules.rules
    mode: "0644"
    owner: root
    group: root
  notify: augenrules
  tags: auditd

- name: 6.3.3.20 Ensure the audit configuration is immutable
  ansible.builtin.copy:
    src: files/auditd/99-finalize.rules
    dest: /etc/audit/rules.d/99-finalize.rules
    mode: "0644"
    owner: root
    group: root
  notify: augenrules
  tags: auditd

# 700 is the default
- name: 6.3.4.1 Ensure the audit log file directory mode is configured
  ansible.builtin.file:
    path: /var/log/audit/
    owner: root
    group: root
    mode: "0700"
  tags: auditd

- name: Find audit logs
  ansible.builtin.find:
    paths: /var/log/audit
    file_type: file
  register: audit_logs
  tags: auditd

# 6.3.4.3 Ensure audit log files owner is configured
# 6.3.4.4 Ensure audit log files group owner is configured
- name: 6.3.4.2 Ensure audit log files mode is configured
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: "u-x,g-rwx,o-rwx"
  with_items: "{{ audit_logs.files }}"
  tags: auditd

# 6.3.4.9 Ensure audit tools owner is configured
# 6.3.4.10 Ensure audit tools group owner is configured
- name: 6.3.4.8 Ensure audit tools mode is configured (auditctl)
  ansible.builtin.file:
    path: /sbin/auditctl
    owner: root
    group: root
    mode: "0755"
  tags: auditd

- name: 6.3.4.8 Ensure audit tools mode is configured (aureport)
  ansible.builtin.file:
    path: /sbin/aureport
    owner: root
    group: root
    mode: "0755"
  tags: auditd

- name: 6.3.4.8 Ensure audit tools mode is configured (ausearch)
  ansible.builtin.file:
    path: /sbin/ausearch
    owner: root
    group: root
    mode: "0755"
  tags: auditd

- name: 6.3.4.8 Ensure audit tools mode is configured (autrace)
  ansible.builtin.file:
    path: /sbin/autrace
    owner: root
    group: root
    mode: "0750"
  tags: auditd

- name: 6.3.4.8 Ensure audit tools mode is configured (augenrules)
  ansible.builtin.file:
    path: /sbin/augenrules
    owner: root
    group: root
    mode: "0755"
  tags: auditd

- name: 6.3.4.8 Ensure audit tools mode is configured (auditd)
  ansible.builtin.file:
    path: /sbin/auditd
    owner: root
    group: root
    mode: "0755"
  tags: auditd
